### ISSUE TITLE
Complier errors beginning with release 1.8.0 to 1.8.2

### ISSUE THREAD

**Issue by Pconti31** [adafruit/Adafruit-GFX-Library#291]
Unable to compile Adafruit_ILI9341/example/graphicstest.inisuccessfully on Arduino Uno,,or Mega, using 1.8.0,1.8.1 and 1.8.2 missing or badly named include file.
works fine with 1.7.6

Alternatives for Adafruit_I2CDevice.h: []
ResolveLibrary(Adafruit_I2CDevice.h)
  -> candidates: []
In file included from C:\Users\Paul\Documents\Arduino\libraries\Adafruit-GFX-Library\Adafruit_MonoOLED.cpp:18:0:

C:\Users\Paul\Documents\Arduino\libraries\Adafruit-GFX-Library\Adafruit_MonoOLED.h:28:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>

          ^~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

Using library SPI at version 1.0 in folder: C:\arduino-1.8.12\hardware\arduino\avr\libraries\SPI 
Using library Adafruit-GFX-Library at version 1.8.0 in folder: C:\Users\Paul\Documents\Arduino\libraries\Adafruit-GFX-Library 
Using library Adafruit_ILI9341 at version 1.5.4 in folder: C:\Users\Paul\Documents\Arduino\libraries\Adafruit_ILI9341 
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

**Comment by PaintYourDragon** [comment]
Adafruit_BusIO is now a dependency. Can install from Library manager or at https://github.com/adafruit/Adafruit_BusIO

**Comment by tushada** [comment]
After trying to resolve the Compilation issue from 3 hours - I found your Your Solution of adding the library for Adafruit_BusIO - it resolved the error. Thanks a lot - you have given the right solution.

**Comment by planktonfun** [comment]
Weird I kept installing Adafruit_BusIO but Im still stuck with
Arduino\libraries\Adafruit_GFX_Library\Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory
 #include <Adafruit_I2CDevice.h>

**Comment by alhubbar673** [comment]
Adding the Adafruit_BusIO to my libraries worked for me!
